import Head from "next/head";
import React from "react";
import { axios } from "../libs/axios";

export default function Home() {
  const [blog, setBlog] = React.useState([]);

  const getBlog = async () => {
    const req = await axios.get("http://localhost:8888/api/blog");
    console.log(req);
    const res = req.data;
    setBlog(res);
  };

  console.log(blog);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello Blog</h1>
      <button onClick={getBlog}>blog</button>
    </div>
  );
}
