import Head from "next/head";
import React from "react";
import Axios from "axios";

const axios = Axios.create({
  baseURL: process.env.API_URL,
  headers: {
    "X-Requested-With": "XMLHttpRequest",
  },
  withCredentials: true,
});

export default function Home() {
  const [blog, setBlog] = React.useState([]);

  const getBlog = async () => {
    const req = await axios.get("http://localhost:8888/api/blog");
    const res = req.data;
    console.log(res);
    setBlog(res);
  };

  console.log(blog);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello Blog</h1>
      <button onClick={getBlog}>blog</button>
    </div>
  );
}
